
server.port=8080


spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.tpvrmtbiytuxffaxjtnr
spring.datasource.password=PTe5CzsiKgAI8obR
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


logging.level.root=INFO
logging.level.edu.cit.jabines=DEBUG